import { ITestUnitsMap } from '../types/test.units.types';
import { ITestCase } from '../types/types';

export const netCases = (units: ITestUnitsMap): ITestCase[] => [
  {
    title: 'Test LEAVE NET over WS',
    dbDataFile: 'restore.sh',
    connection: 'ws',
    caseUnits: [
      [units.account.login.user(1), 1],
      [units.account.login.user(2), 2],
      [units.account.login.user(3), 3],
      [units.account.login.user(4), 4],
      [units.net.enter(1), 1],
      [units.net.enter(1), 2],
      [units.net.enter(1), 3],
      [units.net.enter(1), 4],
      //
      [units.net.leave, 4],
      [units.events.newEvents, 1],
      [units.events.read.leave.connected, 1],
      //
      [units.net.create.second, 1],
      [units.net.enter(2), 1],
      [units.invite.create.tMember(0), 1],
      [units.net.connectByToken.toNet(2), 2],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInTree, 1],
      [units.net.enter(2), 2],
      [units.net.leave, 2],
      [units.net.leave, 1],
      //
      [units.net.enter(1), 1],
      [units.net.create.second, 1],
      [units.net.enter(3), 1],
      [units.invite.create.tMember(0), 1],
      [units.net.connectByToken.toNet(3), 2],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInTree, 1],
      [units.net.leave, 1],
      [units.net.enter(3), 2],
      [units.net.leave, 2],
      //
      [units.net.enter(1), 1],
      [units.net.create.second, 1],
      [units.net.enter(4), 1],
      [units.invite.create.tMember(0), 1],
      [units.net.connectByToken.toNet(4), 2],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInTree, 1],
      [units.net.enter(1), 2],
      [units.net.leave, 2],
      [units.net.enter(1), 1],
      [units.net.leave, 1],
      //
      [units.invite.create.tMember(0), 3],
      [units.net.connectByToken.toNet(1), 2],
      [units.events.newEvents, 3],
      // [units.events.read.connectAndConfirmInTree, 3],
      [units.net.create.second, 3],
      [units.net.enter(5), 3],
      [units.invite.create.tMember(0), 3],
      [units.net.connectByToken.toNet(5), 2],
      [units.events.newEvents, 1],
      // [units.events.read.connectAndConfirmInTree, 1],
      [units.net.enter(1), 3],
      [units.net.leave, 3],
      [units.net.enter(1), 2],
      [units.net.leave, 2],
      [units.net.get.structure(1), 0],
      [units.net.get.structure(5), 0],
      //
      [units.events.check.confirmed, 0],
      [units.net.get.structure(1), 0],
      [units.net.get.structure(2), 0],
      [units.net.get.structure(3), 0],
      [units.net.get.structure(4), 0],
      [units.net.get.structure(5), 0],
    ],
  },
];
